<?php

/**
 * Implements hook_plugin_filter_TYPE_alter().
 */
function context_entity_field_plugin_filter_condition_alter(array &$definitions, array $extra, $consumer) {
  // Keep within the Context UI only.
  if (in_array($consumer, ['block_ui', 'layout_builder'])) {
    foreach ($definitions as $key => &$definition) {
      if ('entity_field' == $definition['id']) {
        unset($definitions[$key]);
      }
    }
  }
}
